core/urls.py
from . import views
from django.urls import path

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('contact/', views.contact, name='contact'),
    path('faqs/', views.faq, name='faq'),
    path('blogs/', views.blog, name='blog_list'),
    path('blogs/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('blogs/categories/<slug:c_slug>/', views.blog, name='blog_list_by_category'),
    path('blogs/tags/<slug:t_slug>/', views.blog, name='blog_list_by_tag'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

instructor/urls.py
from . import views
from django.urls import path, include

app_name = 'instructor'
urlpatterns = [
    path('', views.list, name='list'),
    path('apply/', views.apply, name='apply'),
    path('add_course/', views.add_course, name='add_course'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('reviews/', views.reviews, name='reviews'),
    path('courses/', views.courses, name='courses'),
    path('students/', views.students, name='students'),
    path('<str:username>/', views.details, name='detail'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('courses/', include('course.urls')),
    path('accounts/', include('allauth.urls')),
    path('students/', include('student.urls')),
    path('instructors/', include('instructor.urls')),
    path('users/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('payments/', include('payments.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Educonnect Admin'
admin.site.site_title = 'Educonnect Admin'

user/urls.py
from . import views
from django.urls import path

app_name = 'users'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('social-profiles/', views.social_profile, name='social_profile'),
]

instructor/models.py
from django.db import models

# Create your models here.
class Apply(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE, related_name='application')
    name = models.CharField(max_length=120)
    email = models.EmailField(max_length=200)
    id_number = models.CharField(max_length=20)
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

instructor/forms.py
from django import forms
from user.models import Profile, SocialMedia
from django.contrib.auth.models import User
from course.models import Course
from .models import Apply

class UserForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class ProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    position = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Profile
        fields = ['image','location','phone_number','date_of_birth','position','bio']

class SocialMediaForm(forms.ModelForm):
    class Meta:
        model = SocialMedia
        fields = ['facebook', 'linkedin', 'instagram', 'twitter']


class AddCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'academic_level', 'front_image', 'cover_image', 'category', 'level', 'overview', 'price', 'preview_video', 'has_certificate']

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Apply
        fields = '__all__'
        exclude = ('user','is_approved')

instructor/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q, Count
from django.contrib import messages
from core.models import Location
from instructor.forms import ApplicationForm
from user.models import Profile
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from .forms import AddCourseForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from core.decorators import require_superuser_or_instructor
from course.models import Review
import uuid

# Create your views here.
@login_required
@require_superuser_or_instructor
def dashboard(request):
    context = {
        'title': 'Dashboard',
    }
    return render(request, 'instructor/dashboard.html', context)

@login_required
@require_superuser_or_instructor
def list(request):
    query = request.GET.get('q', None)
    location = request.GET.get('location', None)
    order_by_filter = request.GET.get('f', None)

    instructors = Profile.objects.filter(account_type='instructor', user__is_active=True)

    if query:
        instructors = instructors.filter(Q(user__first_name__icontains=query) | Q(user__last_name__icontains=query))

    if location:
        instructors = instructors.filter(location__title=location)

    if order_by_filter:
        if order_by_filter == 'recent':
            instructors = instructors.order_by('-updated_at')
        elif order_by_filter == 'courses':
            instructors = instructors.annotate(num_courses=Count('user__courses')).order_by('-num_courses')
        elif order_by_filter == 'near':                         
            if request.user.is_authenticated and hasattr(request.user, 'profile') and request.user.profile.location:
                instructors = instructors.filter(location=request.user.profile.location)
            else:
                messages.warning(request, f'Complete your profile to get instructors around you')

    paginator = Paginator(instructors, 20)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)

    context = {
        'title': 'Instructors List',
        'locations': Location.objects.filter(is_active=True),
        'instructors': page_obj
    }

    return render(request, 'instructor/list.html', context)

@login_required
@require_superuser_or_instructor
def details(request, username):
    instructor = get_object_or_404(Profile, user__username=username, user__is_active=True)
    courses = instructor.user.courses.filter(is_active=True)
    query = request.GET.get('q', None)
    if query:
        courses = courses.filter(Q(title__icontains=query))

    paginator = Paginator(courses, 20)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)
    context = {
        'title': instructor.user.get_full_name(),
        'instructor': instructor,
        'courses': page_obj
    }
    return render(request, 'instructor/details.html', context)

@login_required
@require_superuser_or_instructor
def apply(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            try:
                application =  form.save(commit=False)
                application.user=request.user
                application.save()
                messages.success(request, "Applied Successfully!")
                return redirect('core:dashboard')
            except Exception as e:
                messages.warning(request, f"{e}")
                return redirect('instructor:apply')
    else:
        form = ApplicationForm()
    
    context = {
        'title': 'Apply to Become tutor',
        'form': form
    }
    return render(request, 'instructor/apply.html', context)

@login_required
@require_superuser_or_instructor
def courses(request):

    context = {
        'title': 'My Courses',
    }
    return render(request, 'instructor/courses.html', context)

@login_required
@require_superuser_or_instructor
def reviews(request):

    context = {
        'title': 'My Reviews',
        'reviews': Review.objects.filter(course__owner=request.user)
    }
    return render(request, 'instructor/reviews.html', context)

@login_required
@require_superuser_or_instructor
def students(request):

    context = {
        'title': 'My Students',
    }
    return render(request, 'instructor/students.html', context)

@login_required
@require_superuser_or_instructor
def add_course(request):
    user_instance = request.user

    if request.method == 'POST':
        add_course_form = AddCourseForm(request.POST, request.FILES)
        if add_course_form.is_valid():
            course = add_course_form.save(commit=False)
            course.owner = user_instance
            course.slug = slugify(course.title) + '-' + str(uuid.uuid4())[:8]
            course.save()
            messages.success(request, 'Courses Successfully Added!')
            return redirect('instructor:detail', user_instance.username)
    else:
        add_course_form = AddCourseForm()

    context = {
        'title': 'Add Course',
        'add_course_form': add_course_form,
    }
    return render(request, 'instructor/add_course.html', context)

templates/instructor/partials/sidebar.html
<div class="col-xl-3 col-lg-4 col-md-12 theiaStickySidebar">
    <div class="settings-widget dash-profile">
        <div class="settings-menu p-0">
            <div class="profile-bg">
                <img src="/static/img/instructor-profile-bg.jpg" alt>
                <div class="profile-img">
                    <a href="#"><img src="{% if request.user.profile.image %}{{ request.user.profile.image.url }}{% else %}/static/img/user/user15.jpg{% endif %}" alt></a>
                </div>
            </div>
            <div class="profile-group">
                <div class="profile-name text-center">
                    <h4><a href="#">{{ request.user.get_full_name|default:'No Name' }}</a></h4>
                    <p>Instructor</p>
                </div>
                <div class="go-dashboard text-center">
                    <a href="{% url 'instructor:add_course' %}" class="btn btn-primary">Create New Course</a>
                </div>
            </div>
        </div>
    </div>
    <div class="settings-widget account-settings">
        <div class="settings-menu">
            <h3>DASHBOARD</h3>
            <ul>
                <li class="nav-item {% if 'Dashboard' in title %}active{% endif %}">
                    <a href="{% url 'instructor:dashboard' %}" class="nav-link">
                        <i class="feather-home"></i> My Dashboard
                    </a>
                </li>
                <li class="nav-item {% if 'Course' in title %}active{% endif %}">
                    <a href="{% url 'instructor:courses' %}" class="nav-link">
                        <i class="feather-book"></i> My Courses
                    </a>
                </li>
                <li class="nav-item {% if 'Review' in title %}active{% endif %}">
                    <a href="{% url 'instructor:reviews' %}" class="nav-link">
                        <i class="feather-star"></i> Reviews
                    </a>
                </li>
                <li class="nav-item {% if 'Student' in title %}active{% endif %}">
                    <a href="{% url 'instructor:students' %}" class="nav-link">
                        <i class="feather-users"></i> Students
                    </a>
                </li>
            </ul>
            <div class="instructor-title">
                <h3>ACCOUNT SETTINGS</h3>
            </div>
            <ul>
                <li class="nav-item">
                    <a href="{% url 'users:profile' %}" class="nav-link {% if 'My Profile' in title %}active{% endif %}">
                        <i class="feather-settings"></i> My Profile
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'users:edit_profile' %}" class="nav-link {% if 'Edit Profile' in title %}active{% endif %}">
                        <i class="feather-settings"></i> Edit Profile
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'users:social_profile' %}" class="nav-link {% if 'Social Link' in title %}active{% endif %}">
                        <i class="feather-refresh-cw"></i> Social Profiles
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'account_logout' %}" class="nav-link">
                        <i class="feather-power"></i> Sign Out
                    </a>
                </li>
            </ul>
        </div>
    </div>  
</div>