core/urls.py
from . import views
from django.urls import path

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('contact/', views.contact, name='contact'),
    path('faqs/', views.faq, name='faq'),
    path('blogs/', views.blog, name='blog_list'),
    path('blogs/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('blogs/categories/<slug:c_slug>/', views.blog, name='blog_list_by_category'),
    path('blogs/tags/<slug:t_slug>/', views.blog, name='blog_list_by_tag'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('courses/', include('course.urls')),
    path('accounts/', include('allauth.urls')),
    path('students/', include('student.urls')),
    path('instructors/', include('instructor.urls')),
    path('users/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('payments/', include('payments.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Educonnect Admin'
admin.site.site_title = 'Educonnect Admin'

templates/blog/aside.html
<div class="col-lg-3 col-md-12 sidebar-right theiaStickySidebar">

    <div class="card search-widget blog-search blog-widget">
        <div class="card-body">
            <form class="search-form">
                <div class="input-group">
                    <input type="search" placeholder="Search..." class="form-control" name="q" required>
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                </div>
            </form>
        </div>
    </div>

    {% if blogs %}
    <div class="card post-widget blog-widget">
        <div class="card-header">
            <h4 class="card-title">Recent Posts</h4>
        </div>
        <div class="card-body">
            <ul class="latest-posts">
                {% for blog in blogs %}
                <li>
                    <div class="post-thumb">
                        <a href="{{ blog.get_absolute_url }}">
                            <img class="img-fluid" src="{% if blog.front_image %}{{ blog.front_image.url }}{% else %}/static/img/blog/front-default.png{% endif %}" alt>
                        </a>
                    </div>
                    <div class="post-info">
                        <h4>
                            <a href="{{ blog.get_absolute_url }}">{{ blog.title|truncatechars:60 }}</a>
                        </h4>
                        <p><img class="img-fluid" src="/static/img/icon/icon-22.svg" alt>{{ blog.published_at|date}}
                        </p>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}

    {% if categories %}
    <div class="card category-widget blog-widget">
        <div class="card-header">
            <h4 class="card-title">Categories</h4>
        </div>
        <div class="card-body">
            <ul class="categories">
                <li><a href="{% url 'core:blog_list' %}" class="{% if not category%}text-primary{% endif %}"><i class="fas fa-angle-right"></i> All</a></li>
                {% for a_category in categories %}
                <li><a href="{{ a_category.get_blogs_url }}" class="{% if category == a_category %}text-primary{% endif %}"><i class="fas fa-angle-right"></i> {{ a_category.title  }} </a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
    {% if tags %}
    <div class="card tags-widget blog-widget tags-card">
        <div class="card-header">
            <h4 class="card-title">Latest Tags</h4>
        </div>
        <div class="card-body">
            <ul class="tags">
                {% for tag in tags %}
                <li><a href="{{ tag.get_blogs_url }}" class="tag">{{ tag.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
</div>

templates/blog/details.html
{% extends 'core/base.html' %}
{% block content %}

        <section class="course-content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9 col-md-12">

                        <div class="blog">
                            <div class="blog-image">
                                <a href="{{ blog.get_absolute_url }}"><img class="img-fluid" src="{% if blog.cover_image %}{{ blog.cover_image.url }}{% else %}/static/img/blog/cover-default.png{% endif %}"
                                        alt="{{ title }}"></a>
                            </div>
                            <div class="blog-info clearfix">
                                <div class="post-left">
                                    <ul>
                                        <li>
                                            <div class="post-author">
                                                <a href="{{ blog.author.profile.get_absolute_url }}"><img src="{% if blog.author.profile.image %}{{ blog.author.profile.image.url }}{% else %}/static/img/user/default.png{% endif %}"
                                                        alt="{{ blog.author.get_full_name|default:'Anonimous'}}"> <span>{{ blog.author.get_full_name|default:'Anonimous'}}</span></a>
                                            </div>
                                        </li>
                                        <li><img class="img-fluid" src="/static/img/icon/icon-22.svg" alt>{{ blog.published_at }}
                                        </li>
                                        <li><img class="img-fluid" src="/static/img/icon/icon-23.svg" alt>
                                            {% if blog.tags.all %}
                                                {% for tag in blog.tags.all %}
                                                    {{ tag }},  
                                                {% endfor %}
                                            {% endif %}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <h3 class="blog-title"><a href="{{ blog.get_absolute_url }}">{{ title }}</a></h3>
                            <div class="blog-content">
                                {{ blog.description|safe }}
                            </div>
                        </div>

                    </div>

                    {% include 'blog/aside.html' %}

                </div>
            </div>
        </section>

{% endblock %}

templates/blog/index.html
{% extends 'core/base.html' %}
{% block content %}
    <section class="course-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-md-12">
                    <div class="row">
                        {% if blogs %}
                        {% for blog in blogs %}
                            <div class="col-md-6 col-sm-12">

                                <div class="blog grid-blog">
                                    <div class="blog-image">
                                        <a href="{{ blog.get_absolute_url }}"><img class="img-fluid" src="{% if blog.front_image %}{{ blog.front_image.url }}{% else %}/static/img/blog/front-default.png{% endif %}" alt="{{ blog.title }}"></a>
                                    </div>
                                    <div class="blog-grid-box">
                                        <div class="blog-info clearfix">
                                            <div class="post-left">
                                                <ul>
                                                    <li><img class="img-fluid" src="/static/img/icon/icon-22.svg" alt>{{ blog.published_at|date }}</li>
                                                    <li><img class="img-fluid" src="/static/img/icon/icon-23.svg" alt>
                                                        {% if blog.tags.all %}
                                                            {% for tag in blog.tags.all %}
                                                                {{ tag }}, 
                                                            {% endfor %}
                                                        {% endif %}
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                        <h3 class="blog-title"><a href="{{ blog.get_absolute_url }}">{{ blog.title|truncatechars:30 }}</a></h3>
                                        <div class="blog-content blog-read">
                                            <p>{{ blog.get_overview|default:'No Description' }}</p>
                                            <a href="{{ blog.get_absolute_url }}" class="read-more btn btn-primary">Read More</a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        {% endfor %}
                        {% else %}
                        <p class="mx-3">No Blog Post Found</p>
                        {% endif %}
                    </div>
                </div>

                {% include 'blog/aside.html' %}

            </div>
        </div>
    </section>
{% endblock %}