core/urls.py
from . import views
from django.urls import path

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('contact/', views.contact, name='contact'),
    path('faqs/', views.faq, name='faq'),
    path('blogs/', views.blog, name='blog_list'),
    path('blogs/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('blogs/categories/<slug:c_slug>/', views.blog, name='blog_list_by_category'),
    path('blogs/tags/<slug:t_slug>/', views.blog, name='blog_list_by_tag'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('courses/', include('course.urls')),
    path('accounts/', include('allauth.urls')),
    path('students/', include('student.urls')),
    path('instructors/', include('instructor.urls')),
    path('users/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('payments/', include('payments.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Educonnect Admin'
admin.site.site_title = 'Educonnect Admin'

student/urls.py
from . import views
from django.urls import path, include

app_name = 'students'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('reviews/', views.reviews, name='reviews'),
    path('courses/', views.courses, name='courses'),
    path('accounts/', views.accounts, name='accounts'),
    path('profile/', views.profile, name='profile'),
]

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render
from course.models import Course
from django.contrib.auth.decorators import login_required
from core.decorators import require_superuser_or_student
# Create your views here.

@login_required
@require_superuser_or_student
def dashboard(request):
    context = {
        'title': "Dashboard",
        'courses': Course.objects.filter(is_active=True)
    }
    return render(request, 'student/dashboard.html', context)

@login_required
@require_superuser_or_student
def courses(request):
    courses = Course.objects.filter(students=request.user)
    context = {
        'title': "Enrolled Courses",
        'courses': courses
    }
    return render(request, 'student/courses.html', context)

@login_required
@require_superuser_or_student
def reviews(request):
    context = {
        'title': "Reviews Left"
    }
    return render(request, 'student/reviews.html', context)

@login_required
@require_superuser_or_student
def accounts(request):
    context = {
        'title': "Accounts Settings"
    }
    return render(request, 'student/accounts.html', context)

@login_required
@require_superuser_or_student
def profile(request):
    context = {
        'title': "User Profile"
    }
    return render(request, 'student/profile.html', context)

templates/student/partials/topbar.html
<div class="course-student-header">
    <div class="container">
        <div class="student-group">
            <div class="course-group ">
                <div class="course-group-img d-flex">
                    <a href=""><img src="{% if user.profile.image %}{{ user.profile.image.url }}{% else %}/static/img/user/user11.jpg{% endif %}" alt class="img-fluid"></a>
                    <div class="d-flex align-items-center">
                        <div class="course-name">
                            <h4><a href="">{{ request.user.get_full_name|default:'No Name' }}</a><span>{{ request.user.profile.location }}</span></h4>
                            <p>Student</p>
                        </div>
                    </div>
                </div>
                <div class="course-share ">
                    <a href="{% url 'students:accounts' %}" class="btn btn-primary">Account Settings</a>
                </div>
            </div>
        </div>
        <div class="my-student-list">
            <ul>
                <li><a class="{% if 'Dashboard' in title  %}active{% endif %}" href="{% url 'students:dashboard' %}">Dashboard</a></li>
                <li><a class="{% if 'Courses' in title  %}active{% endif %}" href="{% url 'students:courses' %}">Courses</a></li>
                <li><a class="{% if 'Reviews' in title  %}active{% endif %}" href="{% url 'students:reviews' %}">Reviews</a></li>
            </ul>
        </div>
    </div>
</div>